### ISSUE TITLE
ppt文件损坏

### ISSUE THREAD

**Issue by BoZhiStudying233** [MQguer/XDU-CS-Resources#11]
感谢你的分享！
但是我在使用过程中发现 其他文件/各类模板/PPT模板/西电专属PPT模板  下的许多ppt文件损坏了。

**Comment by MQguer** [comment]
感谢指正，这些模板是一位学长制作后发布在公众号的，可能是因为文件太大无法正常上传，如果有需要可以在我网盘自取：
链接：https://pan.baidu.com/s/1NIdTv_6CruVbGHGODx4VxA?pwd=m6fx 
提取码：m6fx

**Comment by BoZhiStudying233** [comment]
感谢！
